version: '3.8'
services:
  database:
    container_name: "sqlserver"
    hostname: "sqlserver"
    ports:
      - "1433:1433"
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Teste12345!"